function needsZeroSub (flag, index, timeStart) {
  return flag && index === 0 && timeStart !== '00:00:00,000'
}

function zeroSub (timeStart) {
  return `1\n00:00:00,000 --> ${timeStart}\nAutomatically generated by moneypenny\n\n`
}

module.exports = {
  needsZeroSub,
  zeroSub
}
